// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using C2TPro;

public static partial class OwnedWeaponsTable
{
	public partial class Row
	{
		public int index;
		public string name;
		public string weapon_type;
		public int damage;
		public int attack_range;
		public int attackspeed;
		public int magazine;
		public int make_magazine;
		public int critical_rate;
		public string weapon_appearance;
		public int bullet_speed;
		public string bullet_appearance;
		public string attack_target;

	}

	static List<Row> rowList = new List<Row>();
	static bool isLoaded = false;

	public static bool IsLoaded()
	{
		return isLoaded;
	}

    public static void Clear()
    {   
        isLoaded = false;
        rowList.Clear();
    }

	public static List<Row> GetRowList()
	{
        StaticLoad();
		return rowList;
	}

	public static void Load(string csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser.Parse(csv);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			if(grid[i][0].StartsWith("#"))
				continue;	// skip comment

			Row row = new Row();
			row.index = string.IsNullOrEmpty(grid[i][0]) ? 0 : Convert.ToInt32(grid[i][0]);
			row.name = grid[i][1];
			row.weapon_type = grid[i][2];
			row.damage = string.IsNullOrEmpty(grid[i][3]) ? 0 : Convert.ToInt32(grid[i][3]);
			row.attack_range = string.IsNullOrEmpty(grid[i][4]) ? 0 : Convert.ToInt32(grid[i][4]);
			row.attackspeed = string.IsNullOrEmpty(grid[i][5]) ? 0 : Convert.ToInt32(grid[i][5]);
			row.magazine = string.IsNullOrEmpty(grid[i][6]) ? 0 : Convert.ToInt32(grid[i][6]);
			row.make_magazine = string.IsNullOrEmpty(grid[i][7]) ? 0 : Convert.ToInt32(grid[i][7]);
			row.critical_rate = string.IsNullOrEmpty(grid[i][8]) ? 0 : Convert.ToInt32(grid[i][8]);
			row.weapon_appearance = grid[i][9];
			row.bullet_speed = string.IsNullOrEmpty(grid[i][10]) ? 0 : Convert.ToInt32(grid[i][10]);
			row.bullet_appearance = grid[i][11];
			row.attack_target = grid[i][12];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public static void StaticLoad()
	{
		if(!isLoaded) 
            Load(Resources.Load<TextAsset>("Table/OwnedWeapons").text);
	}


	public static int NumRows()
	{
        StaticLoad();
		return rowList.Count;
	}

	public static Row GetAt(int i)
	{
        StaticLoad();
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public static Row Find_index(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.index == find);
	}
	public static List<Row> FindAll_index(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.index == find);
	}
	public static Row Find_name(string find)
	{
        StaticLoad();
		return rowList.Find(x => x.name == find);
	}
	public static List<Row> FindAll_name(string find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.name == find);
	}
	public static Row Find_weapon_type(string find)
	{
        StaticLoad();
		return rowList.Find(x => x.weapon_type == find);
	}
	public static List<Row> FindAll_weapon_type(string find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.weapon_type == find);
	}
	public static Row Find_damage(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.damage == find);
	}
	public static List<Row> FindAll_damage(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.damage == find);
	}
	public static Row Find_attack_range(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.attack_range == find);
	}
	public static List<Row> FindAll_attack_range(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.attack_range == find);
	}
	public static Row Find_attackspeed(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.attackspeed == find);
	}
	public static List<Row> FindAll_attackspeed(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.attackspeed == find);
	}
	public static Row Find_magazine(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.magazine == find);
	}
	public static List<Row> FindAll_magazine(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.magazine == find);
	}
	public static Row Find_make_magazine(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.make_magazine == find);
	}
	public static List<Row> FindAll_make_magazine(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.make_magazine == find);
	}
	public static Row Find_critical_rate(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.critical_rate == find);
	}
	public static List<Row> FindAll_critical_rate(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.critical_rate == find);
	}
	public static Row Find_weapon_appearance(string find)
	{
        StaticLoad();
		return rowList.Find(x => x.weapon_appearance == find);
	}
	public static List<Row> FindAll_weapon_appearance(string find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.weapon_appearance == find);
	}
	public static Row Find_bullet_speed(int find)
	{
        StaticLoad();
		return rowList.Find(x => x.bullet_speed == find);
	}
	public static List<Row> FindAll_bullet_speed(int find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.bullet_speed == find);
	}
	public static Row Find_bullet_appearance(string find)
	{
        StaticLoad();
		return rowList.Find(x => x.bullet_appearance == find);
	}
	public static List<Row> FindAll_bullet_appearance(string find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.bullet_appearance == find);
	}
	public static Row Find_attack_target(string find)
	{
        StaticLoad();
		return rowList.Find(x => x.attack_target == find);
	}
	public static List<Row> FindAll_attack_target(string find)
	{
        StaticLoad();
		return rowList.FindAll(x => x.attack_target == find);
	}

}